### ISSUE TITLE
master = production ready?

### ISSUE THREAD

**Issue by vrms** [semilimes/livechat#1]
hi, great initiative and great thing to publish you repo on the erpnext forum right away.

1. I think standard convention in github is that a branch called 'master' is a working software. Is that so (in terms of being stable and save to use) with livechat?
2. is this meant to be used internally. From users of ERPNext to the other or a livechat app to talk to anybody who might contact you through some sort of "livechat" button on your website?

**Comment by frahergal** [comment]
Hello @vrms !
Thank you for your comments and feedback. 

1.- Yes, you are right. The master branch is intended for production, but as I understand, the first push/version should be made also on master and then from that version continue the development on a dev branch. Actually this first version is stable and safe, but it is right now quite simple functionality because we just have started.

2.- This APP is meant to be a livechat app to talk to anybody through the website and also between users on ERPNext. Right now is designed to act between users with defined roles (chat user & agents) but it is just a draft about what will become next.
